[world]
width = 29.8
height = 29.8
workerCount = 4
subStep = 4
disableSleep = false
frameDuration = 0.033333

[puck]
radius = 0.975
gap = 0.0001
bodyLinearDamping = 0.3
bodyAngularDamping = 0.0
shapeFriction = 0.0
shapeRestitution = 0.85
shapeDensity = 2.0

[pocket]
radius = 1.05
cornerOffsetX = 0.0
cornerOffsetY = 0.0

[striker_limit]
width = 0.0
centerOffset = 0.0

[striker]
radius = 1.275
bodyLinearDamping = 0.3
bodyAngularDamping = 0.0
shapeFriction = 0.0
shapeRestitution = 0.85
shapeDensity = 2.0
