[world]
width = 8.81
height = 8.81
workerCount = 4
subStep = 4
disableSleep = false
frameDuration = 0.016666

[puck]
radius = 0.16
gap = 0.0001
bodyLinearDamping = 1.8
bodyAngularDamping = 2.0
shapeFriction = 0.0
shapeRestitution = 1.0
shapeDensity = 0.45

[pocket]
radius = 0.22
cornerOffsetX = 0.0
cornerOffsetY = 0.0

[striker_limit]
width = 5.0
centerOffset = 3.5
maxForce = 150.0

[striker]
radius = 0.2176
bodyLinearDamping = 2.8
bodyAngularDamping = 5.0
shapeFriction = 0.0
shapeRestitution = 1.0
shapeDensity = 0.5